modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "sop"
version = "${version}"
displayName = "Songs Of Power"
authors = "IAFEnvoy"
description = '''
Add song abilities from Songs of War Animation.
'''
logoFile = "logo.jpg"

[[dependencies.sop]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sop]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sop]]
modId = "jupiter"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sop]]
modId = "neptune"
mandatory = true
versionRange = "[1.4.2,)"
ordering = "NONE"
side = "BOTH"